version: '3.8'

services:
  snippetManagerDB:
    image: postgres:latest
    ports:
      - "5433:5433"
    env_file:
      - .env

  snipperManagerAPI:
    image: snippetmanagerapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - snippetManagerDB
    env_file:
      - .env


volumes:
  postgres_data:
