version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - .env

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
